// Automatically generated by astro-icon
// 5ae8fe332512ef9121796491654a1e615dbe3ccd6c16a7249c21f3e46c06aa29

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "social/facebook"
		| "social/github"
		| "social/linkedin"
		| "social/x";
}