// Automatically generated by astro-icon
// 7402032aab9356d4ddb4ec3f1be519b4c97074010894ad026af29df145367f47

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-left"
		| "arrow-right"
		| "prog_lang/astro"
		| "prog_lang/cplusplus"
		| "prog_lang/css3"
		| "prog_lang/html5"
		| "prog_lang/python"
		| "prog_lang/typescript"
		| "social/facebook"
		| "social/github"
		| "social/linkedin"
		| "social/x";
}