// Automatically generated by astro-icon
// 5c1ec559090429252a6f5d21ac40e18009a41b860e4159074da4e96b673303d0

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "prog_lang/astro"
		| "prog_lang/cplusplus"
		| "prog_lang/css3"
		| "prog_lang/html5"
		| "prog_lang/python"
		| "prog_lang/typescript"
		| "social/facebook"
		| "social/github"
		| "social/linkedin"
		| "social/x";
}